
service: rest-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage : dev
  region : eu-central-1
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

functions:
  getAll:
    handler: handler.getAll
    events:
      - http:
          method: get
          path: /getAll
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          method: get
          path: /getOne/{_id}
          cors: true
  create:
    handler: handler.create
    events:
      - http:
          method: post
          path: /create
          cors: true
  edit:
    handler: handler.edit
    events:
      - http:
          method: put
          path: /edit/{_id}
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          method: delete
          path: /delete/{_id}
          cors: true